In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('../Model/Backup/historico_otimizacao.csv').sort_values(by='iou_wu', ascending=False)
df

,trial,timestamp,model_id,status,iou_wu,faultCount_max,faultCount_min,faultCurveMax,faultCurveProb,faultDecaySigma_max,...,noiseLevel_max,noiseLevel_min,shearGradient_max,shearGradient_min,shearOffset_max,shearOffset_min,waveletDt,waveletDuration,waveletFreq_max,waveletFreq_min
69,95,2026-06-20T11:29:47.119700,model_71,COMPLETE,0.699961,10,6,9.443515,0.498589,70,...,0.629820,0.011732,0.027958,-0.112402,3.410098,-8.855355,0.001042,0.096104,97,86
85,111,2026-06-21T21:51:06.667300,model_87,COMPLETE,0.696620,10,6,8.353575,0.012671,65,...,0.629047,0.017301,0.020806,-0.102924,3.156344,-8.588393,0.001112,0.104206,94,86
72,98,2026-06-20T18:00:16.818727,model_74,COMPLETE,0.694545,10,6,8.917585,0.065651,64,...,0.591749,0.011630,0.025458,-0.118821,4.027444,-9.015815,0.001267,0.095550,98,71
65,91,2026-06-20T02:57:55.708300,model_67,COMPLETE,0.682870,12,6,11.391532,0.049636,77,...,0.574530,0.011517,0.029275,-0.126440,2.830040,-8.693494,0.001539,0.090269,98,83
89,115,2026-06-22T06:12:11.355028,model_91,COMPLETE,0.681836,8,6,6.177666,0.024165,69,...,0.627387,0.014000,0.023438,-0.104630,4.000608,-8.503691,0.000837,0.101953,101,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,10,2026-06-11T20:22:07.992178,model_10,COMPLETE,0.216417,4,3,1.037522,0.687425,87,...,0.677664,0.019269,0.031305,-0.147456,0.909922,-7.222081,0.003597,0.078805,252,115
3,4,2026-06-11T04:35:18.810433,model_5,COMPLETE,0.199859,10,1,2.510694,0.675591,125,...,0.376741,0.030478,0.068162,-0.052757,3.703308,-9.492713,0.000666,0.057029,161,72
0,1,2026-06-10T18:28:11.538217,model_2,COMPLETE,0.192165,9,4,4.645269,0.080193,64,...,0.247999,0.040420,0.020861,-0.166987,1.863687,-9.664270,0.004845,0.143355,97,41
5,7,2026-06-11T11:22:09.037501,model_7,COMPLETE,0.151409,15,2,6.106820,0.300314,156,...,0.420540,0.034801,0.049865,-0.195623,2.605793,-4.053027,0.004713,0.092384,125,55
7,9,2026-06-11T16:59:27.136944,model_9,COMPLETE,0.123545,14,6,4.326124,0.529633,119,...,0.059356,0.037892,-0.002845,-0.185878,3.792286,-9.020845,0.002102,0.052205,193,83

In [11]:
df.loc[df.status == 'FAIL']

Empty DataFrame
Columns: [trial, timestamp, model_id, status, iou_wu, faultCount_max, faultCount_min, faultCurveMax, faultCurveProb, faultDecaySigma_max, faultDecaySigma_min, faultDipAngle_max, faultDipAngle_min, faultRoughSigma, faultRoughness, faultThreshold, faultThrow_max, faultThrow_min, faultZoneWidth, foldAmplitude_max, foldAmplitude_min, foldBaseShift_max, foldBaseShift_min, foldCount_max, foldCount_min, foldDamping, foldSigma_max, foldSigma_min, layerRange_max, layerRange_min, layerThickness_max, layerThickness_min, noiseLevel_max, noiseLevel_min, shearGradient_max, shearGradient_min, shearOffset_max, shearOffset_min, waveletDt, waveletDuration, waveletFreq_max, waveletFreq_min]
Index: []

[0 rows x 42 columns]